version: '3'
services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/web
    command: rails new . --database=postgresql
    links: 
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=web
